export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    DASHBOARD: '/dashboard',
    HISTORY: '/history',
    ANALYTICS: '/analytics',
    COVER_LETTER: '/cover-letter',
    COVER_LETTER_HISTORY: '/cover-letter/history',
    COMPARE: '/compare',
    DOWNLOAD_RESUME: '/resume/download',
    CHAT: '/chat',
};

export const API_ROUTES = {
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
    },
    RESUME: {
        ANALYZE: '/resume/analyze',
        ANALYZE_UPLOAD: '/resume/analyze/upload',
        HISTORY: '/resume/history',
        ANALYTICS: '/resume/analytics',
        HISTORY_ITEM: (id: string) => `/resume/history/${id}`,
        CHAT: '/resume/chat',
    },
    COVER_LETTER: {
        GENERATE: '/cover-letter/generate',
        HISTORY: '/cover-letter/history',
        HISTORY_ITEM: (id: string) => `/cover-letter/history/${id}`,
    },
};

export const STORAGE_KEYS = {
    TOKEN: 'auth_token',
    USER: 'user_data',
};

export const LABELS = {
    APP_NAME: 'ResumeAI',
    ANALYZE: 'Analyze',
    HISTORY: 'History',
    ANALYTICS: 'Analytics',
    LOGOUT: 'Logout',
    LOGIN: 'Login',
    SIGN_UP: 'Sign Up',
    STRENGTHS: 'Strengths',
    WEAKNESSES: 'Weaknesses',
    SUGGESTIONS: 'Improvement Suggestions',
    SUBMIT: 'Submit for Analysis',
    PASTE_RESUME: 'Paste your resume text here...',
    SELECT_FILE: 'Select PDF file',
    FILE_SELECTED: 'File selected',
    ANALYZING: 'Analyzing...',
    REGISTER: 'Register',
    ALREADY_HAVE_ACCOUNT: 'Already have an account?',
    DONT_HAVE_ACCOUNT: 'Don\'t have an account?',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    AUTH_FAILED: 'Authentication failed',
    USER_NOT_FOUND: 'User not found',
    RESUME_ANALYSIS_FAILED: 'Resume analysis failed',
    FETCH_HISTORY_FAILED: 'Failed to fetch history',
    NO_HISTORY: 'No analysis history found',
    BACK_TO_LOGIN: 'Back to Login',
    RESUME_TEXT: 'Resume text',
    TARGET_JOB_DESCRIPTION: 'Target job description (optional)',
    JOB_DESCRIPTION_PLACEHOLDER: 'Paste the job description here to get tailored feedback for this specific role...',
    PASTE_TEXT: 'Paste Text',
    UPLOAD_PDF: 'Upload PDF',
    PAGE_TITLE: 'Resume Analysis',
    PAGE_DESCRIPTION: 'Get AI-powered insights to improve your resume',
    FILE_UPLOAD_HINT: 'Click to select or drag and drop a PDF file',
    MAX_FILE_SIZE: 'Maximum file size: 5MB',
    LOADING: 'Loading...',
    LOAD_MORE: 'Load More',
    NO_ANALYSIS_HISTORY: 'No Analysis History',
    VIEW_PAST_ANALYSES: 'View your past resume analyses',
    SHOWING_ANALYSES: 'Showing',
    OF_ANALYSES: 'of',
    ANALYSES: 'analyses',
    RESUME_SCORE: 'Resume Score',
    SCORE_SUMMARY: 'Summary',
    KEYWORDS_PRESENT: 'Keywords in resume',
    KEYWORDS_MISSING: 'Keywords to add',
    EXPORT_PDF: 'Export PDF',
    DELETE: 'Delete',
    CONFIRM: 'Confirm',
    CANCEL: 'Cancel',
    DELETE_TITLE: 'Delete analysis',
    CONFIRM_DELETE: 'Are you sure you want to delete this analysis?',
    DELETE_FAILED: 'Failed to delete analysis',
    VIEW_ANALYSIS: 'View Analysis',
    HIDE_ANALYSIS: 'Hide Analysis',
    ANALYTICS_TITLE: 'Resume Analytics',
    ANALYTICS_DESCRIPTION: 'Track your resume improvement over time',
    SCORE_TRENDS: 'Score Trends',
    KEYWORD_USAGE: 'Top Keywords',
    AVERAGE_SCORE: 'Average Score',
    LATEST_SCORE: 'Latest Score',
    SCORE_IMPROVEMENT: 'Score Improvement',
    TOTAL_ANALYSES: 'Total Analyses',
    TOTAL_KEYWORDS: 'Total Keywords',
    RESUME_LENGTH: 'Resume Length',
    FORMATTING_ISSUES: 'Formatting Issues',
    ATS_COMPATIBILITY: 'ATS Compatibility',
    WORD_COUNT: 'Word Count',
    PAGE_ESTIMATE: 'Page Estimate',
    OPTIMAL: 'Optimal',
    TOO_SHORT: 'Too Short',
    TOO_LONG: 'Too Long',
    NO_ANALYTICS_DATA: 'No analytics data available. Start analyzing resumes to see your progress!',
    COVER_LETTER: 'Cover Letter',
    COVER_LETTER_TITLE: 'Cover Letter Generator',
    COVER_LETTER_DESCRIPTION: 'Generate a personalized cover letter based on your resume and job description',
    COVER_LETTER_HISTORY: 'Cover Letter History',
    COVER_LETTER_HISTORY_DESCRIPTION: 'View and manage your generated cover letters',
    NO_COVER_LETTER_HISTORY: 'No Cover Letter History',
    NO_COVER_LETTERS: 'You haven\'t generated any cover letters yet. Start by creating your first cover letter!',
    GENERATE_COVER_LETTER: 'Generate Cover Letter',
    COVER_LETTER_PLACEHOLDER: 'Your generated cover letter will appear here...',
    USE_RESUME_FROM_HISTORY: 'Use Resume from History',
    SELECT_RESUME: 'Select Resume',
    NO_RESUME_SELECTED: 'No resume selected',
    COVER_LETTER_GENERATED: 'Cover letter generated successfully',
    GENERATING: 'Generating...',
    COMPARE: 'Compare',
    COMPARE_TITLE: 'Resume Comparison',
    COMPARE_DESCRIPTION: 'Compare two resume analyses side-by-side and track improvements',
    SELECT_BEFORE: 'Before (older)',
    SELECT_AFTER: 'After (newer)',
    SCORE_CHANGE: 'Score change',
    KEYWORDS_ADDED: 'Keywords added',
    KEYWORDS_REMOVED: 'Keywords removed',
    IMPROVEMENTS: 'Improvements',
    NEED_AT_LEAST_TWO: 'You need at least 2 analyses to compare. Analyze more resumes first.',
    GRAMMAR_AND_TONE: 'Grammar & Tone',
    GRAMMAR_AND_TONE_SUMMARY: 'Summary',
    SPELLING_ISSUES: 'Spelling',
    GRAMMAR_ISSUES: 'Grammar',
    TONE_SUGGESTIONS: 'Professional tone',
    NO_GRAMMAR_ISSUES: 'No grammar or spelling issues found.',
    SUGGESTED_CHANGE: 'Suggested change',
    DOWNLOAD_RESUME_LABEL: 'Download Resume',
    DOWNLOAD_RESUME_TITLE: 'Formatted Resume Download',
    DOWNLOAD_RESUME_DESCRIPTION: 'Export your resume as a formatted PDF or DOCX using a template. Optionally include a cover letter.',
    SELECT_RESUME_TO_EXPORT: 'Select resume to export',
    SELECT_TEMPLATE: 'Template',
    EXPORT_FORMAT: 'Format',
    FORMAT_PDF: 'PDF',
    FORMAT_DOCX: 'DOCX',
    INCLUDE_COVER_LETTER: 'Include cover letter',
    SELECT_COVER_LETTER: 'Select cover letter',
    NO_RESUME_HISTORY: 'No resumes in history. Analyze a resume first.',
    NO_COVER_LETTERS_OPTIONAL: 'No cover letters yet. You can still export the resume without one.',
    DOWNLOAD: 'Download',
    NAV_MENU: 'Menu',
    CHAT: 'Chat',
    CHAT_TITLE: 'Resume Chat Assistant',
    CHAT_DESCRIPTION: 'Ask questions about your resume, get improvement suggestions, and request updates. The AI will answer based on your selected resume.',
    SELECT_RESUME_FOR_CHAT: 'Select a resume to chat about',
    TYPE_YOUR_QUESTION: 'Type your question here...',
    SEND: 'Send',
    CLEAR_CHAT: 'Clear Chat',
    UPDATED_RESUME: 'Updated Resume',
    DOWNLOAD_UPDATED_RESUME: 'Download Updated Resume',
    NO_RESUME_SELECTED_CHAT: 'Please select a resume first',
    EXAMPLE_QUESTIONS: 'Example questions',
    EXAMPLE_Q1: 'What are the strengths of my resume?',
    EXAMPLE_Q2: 'How can I improve my resume?',
    EXAMPLE_Q3: 'Implement the suggested improvements',
    EXAMPLE_Q4: 'Update my resume to be more ATS-friendly',
};

export const NAV_LINKS = [
    { to: ROUTES.DASHBOARD, label: LABELS.ANALYZE },
    { to: ROUTES.HISTORY, label: LABELS.HISTORY },
    { to: ROUTES.COMPARE, label: LABELS.COMPARE },
    { to: ROUTES.ANALYTICS, label: LABELS.ANALYTICS },
    { to: ROUTES.COVER_LETTER, label: LABELS.COVER_LETTER },
    { to: ROUTES.DOWNLOAD_RESUME, label: LABELS.DOWNLOAD_RESUME_LABEL },
    { to: ROUTES.CHAT, label: LABELS.CHAT },
];

export const NAV_ICON_MAP: Record<string, string> = {
    [ROUTES.DASHBOARD]: 'FileSearch',
    [ROUTES.HISTORY]: 'History',
};
